version: "3.9"

services:
  agent-dev:
    image: powerpool/power-agent-node:dev
    restart: always
    networks:
      - default
    depends_on:
      - offchain-service
    volumes:
      - ./config:/usr/app/config
      - ./keys:/usr/app/keys
    ports:
      - "8099:8099"
    environment:
      NODE_ENV: ${NODE_ENV}
    profiles: []

  offchain-service:
    container_name: offchain-service
    build: .
    networks:
      - default
      - ipfs_net
    depends_on:
      - temp-executor
    restart: always
    volumes:
      - ./scriptsBuild:/scriptsBuild:ro
      - ./scriptsFetched:/scriptsFetched
      - ./scriptToExecute:/scriptToExecute
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3423:3423"
    environment:
      COMPOSE_MODE: 1
    profiles: [ipfs-test]

  ipfs:
    image: "ipfs/kubo:v0.29.0"
    networks:
      ipfs_peers:
      ipfs_net:
        aliases:
          - ipfs-service
    depends_on:
      - offchain-service
    restart: always
    environment:
      - IPFS_PROFILE
    entrypoint: ["/bin/sh", "-c", "ipfs init; ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001 && ipfs daemon"]
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    volumes:
      - "${IPFS_EXPORT:-./ipfs-export}:/export"
      - "${IPFS_DATA:-./ipfs-data}:/data/ipfs"
    profiles: [ipfs-test]

  temp-executor:
    image: node:18-alpine

networks:
  ipfs_peers:
  ipfs_net:
    internal: true
  default:
    driver: bridge