networks:
  enabled:
    - linea
  details:
    linea:
      rpc: 'wss://rpc.linea.build'
      block_logs_mode: true
      agents:
        '0x20D4029c783D5c9f47569940c656Af4189e53799':
          data_source: subgraph
          subgraph_url: https://subq.powerpool.finance:2053/linea/
          executor: pga
          keeper_worker_address: '0x840ccc99c425edcafebb0e7ccac022cd15fd49ca'
          key_pass: 'PowerPool#TheGreat'
          accrue_reward: false
